# Generated by Django 4.1.1 on 2022-09-22 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wallet",
            options={"ordering": ["-modified_on"]},
        ),
        migrations.AlterField(
            model_name="transaction",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receive_wallet",
                to="api.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="send_wallet",
                to="api.wallet",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="type",
            field=models.CharField(
                choices=[("v", "Visa"), ("m", "Mastercard")], default="v", max_length=1
            ),
        ),
    ]
